version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mailersuite2_prod
      POSTGRES_USER: mailersuite
      POSTGRES_PASSWORD: mailersuite_secure_2024
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/env.production
    environment:
      DATABASE_URL: postgresql+asyncpg://mailersuite:mailersuite_secure_2024@postgres:5432/mailersuite2_prod
      REDIS_URL: redis://redis:6379/0
      HOST: 0.0.0.0
      PORT: 8000
      WORKERS: 4
      # Allow synchronous DB URL override for Alembic when needed (dev override)
      SYNC_DATABASE_URL: ${SYNC_DATABASE_URL:-}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./backend
    env_file:
      - ./backend/env.production
    environment:
      DATABASE_URL: postgresql+asyncpg://mailersuite:mailersuite_secure_2024@postgres:5432/mailersuite2_prod
      REDIS_URL: redis://redis:6379/0
      # Allow synchronous DB URL override for tooling when needed (dev override)
      SYNC_DATABASE_URL: ${SYNC_DATABASE_URL:-}
    command: bash -lc "celery -A core.celery_app:celery_app worker --loglevel=info --concurrency=4"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  flower:
    build:
      context: ./backend
    env_file:
      - ./backend/env.production
    environment:
      DATABASE_URL: postgresql+asyncpg://mailersuite:mailersuite_secure_2024@postgres:5432/mailersuite2_prod
      REDIS_URL: redis://redis:6379/0
    command: bash -lc "flower -A core.celery_app:celery_app --port=5555 --url_prefix=/flower"
    depends_on:
      - worker
    ports:
      - "5555:5555"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: /api/v1
        VITE_WS_URL: /api/v1/ws
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata: