/* tslint:disable */
/* eslint-disable */
/**
 * SGPT API
 * 📧 Professional Email Marketing & IMAP Management Platform
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosRequestConfig } from 'axios';
import axiosInstance from '@/http/axios'
import type { AxiosInstance } from 'axios'
const globalAxios: AxiosInstance = axiosInstance;
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setBearerAuthToObject, setSearchParams, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, BaseAPI, RequiredError, operationServerMap } from './base';
// @ts-ignore
import type { HTTPValidationError } from './models';
/**
 * BlacklistApi - axios parameter creator
 * @export
 */
export const BlacklistApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Check domain against reputation services
         * @summary Check Domain Blacklist
         * @param {string} domain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet: async (domain: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet', 'domain', domain)
            const localVarPath = `/api/v1/blacklist/domain/{domain}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Check IP against DNSBL blacklists
         * @summary Check Ip Blacklist
         * @param {string} ip 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkIpBlacklistApiV1BlacklistBlacklistIpIpGet: async (ip: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ip' is not null or undefined
            assertParamExists('checkIpBlacklistApiV1BlacklistBlacklistIpIpGet', 'ip', ip)
            const localVarPath = `/api/v1/blacklist/ip/{ip}`
                .replace(`{${"ip"}}`, encodeURIComponent(String(ip)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BlacklistApi - functional programming interface
 * @export
 */
export const BlacklistApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BlacklistApiAxiosParamCreator(configuration)
    return {
        /**
         * Check domain against reputation services
         * @summary Check Domain Blacklist
         * @param {string} domain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet(domain: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<unknown>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet(domain, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlacklistApi.checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Check IP against DNSBL blacklists
         * @summary Check Ip Blacklist
         * @param {string} ip 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkIpBlacklistApiV1BlacklistBlacklistIpIpGet(ip: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<unknown>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkIpBlacklistApiV1BlacklistBlacklistIpIpGet(ip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlacklistApi.checkIpBlacklistApiV1BlacklistBlacklistIpIpGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BlacklistApi - factory interface
 * @export
 */
export const BlacklistApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BlacklistApiFp(configuration)
    return {
        /**
         * Check domain against reputation services
         * @summary Check Domain Blacklist
         * @param {string} domain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet(domain: string, options?: RawAxiosRequestConfig): AxiosPromise<unknown> {
            return localVarFp.checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet(domain, options).then((request) => request(axios, basePath));
        },
        /**
         * Check IP against DNSBL blacklists
         * @summary Check Ip Blacklist
         * @param {string} ip 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkIpBlacklistApiV1BlacklistBlacklistIpIpGet(ip: string, options?: RawAxiosRequestConfig): AxiosPromise<unknown> {
            return localVarFp.checkIpBlacklistApiV1BlacklistBlacklistIpIpGet(ip, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BlacklistApi - object-oriented interface
 * @export
 * @class BlacklistApi
 * @extends {BaseAPI}
 */
export class BlacklistApi extends BaseAPI {
    /**
     * Check domain against reputation services
     * @summary Check Domain Blacklist
     * @param {string} domain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlacklistApi
     */
    public checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet(domain: string, options?: RawAxiosRequestConfig) {
        return BlacklistApiFp(this.configuration).checkDomainBlacklistApiV1BlacklistBlacklistDomainDomainGet(domain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Check IP against DNSBL blacklists
     * @summary Check Ip Blacklist
     * @param {string} ip 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlacklistApi
     */
    public checkIpBlacklistApiV1BlacklistBlacklistIpIpGet(ip: string, options?: RawAxiosRequestConfig) {
        return BlacklistApiFp(this.configuration).checkIpBlacklistApiV1BlacklistBlacklistIpIpGet(ip, options).then((request) => request(this.axios, this.basePath));
    }
}

